from pony import orm

T_STATUS_SUBMITTED = 0
T_STATUS_IN_BLOCK = 1
T_STATUS_ERROR = 2

C_STATUS_PENDING = 0
C_STATUS_OMITTED = 1
C_STATUS_REORDERED = 2
C_STATUS_FULFILLED = 2
C_STATUS_REVOKED = 3
C_STATUS_UNEXPECTED = 4

# PonyORM set up
db = orm.Database()
