name: Push the image to Docker registry

on:
  workflow_call:

jobs:
  just_push:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/image.tar
          docker image ls -a

      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Push image
        run: |
          REGISTRY="${{ vars.REGISTRY }}"
          IMAGE_NAME="${{ vars.DOCKER_IMAGE_NAME }}"
          FULL_IMAGE_NAME="${REGISTRY}/${IMAGE_NAME}"
          echo "Pushing image: $FULL_IMAGE_NAME"
          docker push --all-tags $FULL_IMAGE_NAME
