name: Test, build, push

on:
  workflow_dispatch:
    inputs:
      push:
        description: 'Push to registry'
        required: true
        type: boolean
        default: false

jobs:
  run_tests:
    uses: ./.github/workflows/test.yaml

  build:
    needs: [run_tests]
    permissions:
      contents: write
      packages: write
    secrets: inherit
    uses: ./.github/workflows/build.yaml

  push:
    needs: [build]
    secrets: inherit
    uses: ./.github/workflows/push_to_registry.yaml
