name: Test, build, push

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
    paths-ignore:
      - 'releases/**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      push:
        description: 'Push to registry'
        required: true
        type: boolean
        default: false

jobs:
  run_tests_before_build:
    uses: ./.github/workflows/test.yaml

  build_after_tests:
    needs: [run_tests_before_build]
    permissions:
      contents: write
      packages: write
    secrets: inherit
    uses: ./.github/workflows/build_web.yaml
    with:
      push: ${{ github.event_name == 'workflow_dispatch' && inputs.push }}
